language: node_js
node_js:
  - 'stable'

before_install:
  - yarn
  - yarn workspace dukascopy-core run build

script:
  - yarn workspaces run type-check
  - yarn workspaces run test

cache:
  yarn: true
  directories:
    - node_modules
